#!/bin/sh

### BEGIN INIT INFO
# Provides:          tomcat-servers
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Tomcat servers.
# Description:       Start managed Tomcat servers.
### END INIT INFO


ENV="env -i LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Script
# ---------------------------------------------------------------

COMMAND=$1
INSTANCE=""
MANAGER_COMMAND="/usr/sbin/tomcat-server-manager"

if [ -n "$2" ];
  then
    COMMAND=$1
    INSTANCE=$2
fi

console() {
  #$1 = instance
  $MANAGER_COMMAND start-console --instance-name=$1
}

start() {
  #$1 = instance
  logger -p syslog.info "Starting Tomcat instance $1"
  $MANAGER_COMMAND start-instance --instance-name=$1
}

restart() {
  #$1 = instance
  logger -p syslog.info "Restarting Tomcat instance $1"
  $MANAGER_COMMAND restart-instance --instance-name=$1
}

condrestart() {
  #$1 = instance
  $MANAGER_COMMAND condrestart-instance --instance-name=$1
}

dump() {
  #$1 = instance
  $MANAGER_COMMAND dump-instance --instance-name=$1
}


status() {
  #$1 = instance
  $MANAGER_COMMAND status-instance --instance-name=$1
}

stop() {
  #$1 = instance
  logger -p syslog.info "Stopping Tomcat instance $1"
  $MANAGER_COMMAND stop-instance --instance-name=$1
}

execCommand() {
  #$1 = command
  if [ -z "$INSTANCE" ]; then
    # If no instance is specified, apply to all instances
    for instance in $INSTANCES; do $1 $instance; done;
  else
    # If instance is specified, only apply to the instance
    $1 $INSTANCE
  fi
}

# Main switch for init.d commands
INSTANCES=`/usr/sbin/tomcat-server-manager list-instances`
case "$COMMAND" in

    'console')
        if [ -z "$INSTANCE" ];  
          then
            echo "Error: The console command can only be used with an instance name"
            exit 1
        fi
        console $INSTANCE
        ;;

    'start')
        execCommand start
        ;;

    'stop')
        execCommand stop
        ;;

    'restart')
        execCommand restart
        ;;

    'condrestart')
        execCommand condrestart
        ;;

    'status')
        execCommand status
        ;;

    'force-reload')
        execCommand restart
        ;;

    'dump')
        execCommand dump
        ;;
    *)
        echo "Usage: $0 [instance] { console | start | stop | restart | condrestart | force-reload | status | dump }"
        exit 1
        ;;

esac

exit 0

